-- Create database
CREATE DATABASE IF NOT EXISTS `gamepickd-db`;
USE `gamepickd-db`;

-- Drop tables if they exist (in reverse order of creation due to FK constraints)
DROP TABLE IF EXISTS GAMES_PLATFORMS;
DROP TABLE IF EXISTS GAMES_GENRES;
DROP TABLE IF EXISTS GAMES;
DROP TABLE IF EXISTS PUBLISHERS;
DROP TABLE IF EXISTS PLATFORMS;
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS CONTRIBUTORS;
DROP TABLE IF EXISTS USERS_AUTHORITIES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS AUTHORITY_TYPE;

-- Create tables with named constraints

CREATE TABLE AUTHORITY_TYPE (
    AUTHORITY_TYPE_ID INT AUTO_INCREMENT,
    LABEL VARCHAR(128),
    CONSTRAINT AUTHORITY_TYPE_ID_PK PRIMARY KEY (AUTHORITY_TYPE_ID),
    CONSTRAINT AUTHORITY_TYPE_LABEL_UK UNIQUE (LABEL)
);

CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT,
    USERNAME VARCHAR(128),
    EMAIL VARCHAR(128),
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED CHAR(1) NOT NULL,
    CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USER_NAME_UK UNIQUE (USERNAME),
    CONSTRAINT USER_EMAIL_UK UNIQUE (EMAIL),
    CONSTRAINT USER_ENABLED_CK CHECK (ENABLED IN ('Y','N'))
);

CREATE TABLE USERS_AUTHORITIES (
    USER_ID BIGINT NOT NULL,
    AUTHORITY_TYPE_ID INT NOT NULL,
    CONSTRAINT USERS_AUTHORITIES_PK PRIMARY KEY (USER_ID, AUTHORITY_TYPE_ID),
    CONSTRAINT USERS_AUTHORITIES_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT USERS_AUTHORITIES_AUTHORITY_FK FOREIGN KEY (AUTHORITY_TYPE_ID) REFERENCES AUTHORITY_TYPE (AUTHORITY_TYPE_ID)
);

CREATE TABLE MEMBERS (
    MEMBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    CONSTRAINT MEMBER_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT MEMBER_USER_UK UNIQUE (USER_ID)
);

CREATE TABLE CONTRIBUTORS (
    CONTRIBUTOR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    CONSTRAINT CONTRIBUTOR_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT CONTRIBUTOR_USER_UK UNIQUE (USER_ID)
);

CREATE TABLE GENRES (
    GENRE_ID BIGINT AUTO_INCREMENT,
    LABEL VARCHAR(50),
    CONSTRAINT GENRE_ID_PK PRIMARY KEY (GENRE_ID),
    CONSTRAINT GENRE_LABEL_UK UNIQUE (LABEL)
);

CREATE TABLE PUBLISHERS (
    PUBLISHER_ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PUBLISHER_ID_PK PRIMARY KEY (PUBLISHER_ID),
    CONSTRAINT PUBLISHER_NAME_UK UNIQUE (NAME)
);

CREATE TABLE PLATFORMS (
    PLATFORM_ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PLATFORM_ID_PK PRIMARY KEY (PLATFORM_ID),
    CONSTRAINT PLATFORM_NAME_UK UNIQUE (NAME)
);

-- GAMES
CREATE TABLE GAMES (
    GAME_ID BIGINT AUTO_INCREMENT,
    CONTRIBUTOR_ID BIGINT NOT NULL,
    PUBLISHER_ID BIGINT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    COVER_IMAGE_PATH VARCHAR(200),
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    CONSTRAINT GAME_ID_PK PRIMARY KEY (GAME_ID),
    CONSTRAINT GAME_TITLE_UK UNIQUE (TITLE),
    CONSTRAINT GAME_CONTRIBUTOR_FK FOREIGN KEY (CONTRIBUTOR_ID) REFERENCES CONTRIBUTORS(CONTRIBUTOR_ID),
    CONSTRAINT GAME_PUBLISHER_FK FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(PUBLISHER_ID)
);

CREATE TABLE GAMES_GENRES (
    GAME_ID BIGINT,
    GENRE_ID BIGINT,
    CONSTRAINT GAMEGENRE_PK PRIMARY KEY (GAME_ID, GENRE_ID),
    CONSTRAINT GAMEGENRE_GAME_FK FOREIGN KEY (GAME_ID) REFERENCES GAMES(GAME_ID),
    CONSTRAINT GAMEGENRE_GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID)
);

CREATE TABLE GAMES_PLATFORMS (
    GAME_ID BIGINT NOT NULL,
    PLATFORM_ID BIGINT NOT NULL,
    CONSTRAINT GAMEPLATFORM_PK PRIMARY KEY (GAME_ID, PLATFORM_ID),
    CONSTRAINT GAMEPLATFORM_GAME_FK FOREIGN KEY (GAME_ID) REFERENCES GAMES(GAME_ID),
    CONSTRAINT GAMEPLATFORM_PLATFORM_FK FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORMS(PLATFORM_ID)
);


-- Insert Authority Types
INSERT INTO AUTHORITY_TYPE (LABEL) VALUES
('ROLE_ADMIN'),
('ROLE_CONTRIBUTOR'),
('ROLE_MEMBER');

-- Insert Users with clearer role-based usernames
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED, EMAIL) VALUES
('admin',  '$2a$10$S.g6r.ug0CAHKEyPnV5KEu.PCSjh01/xcduj5Ufntpk567lOUI0/a', 'Y', 'admin@example.com'),
('member', '$2a$10$S.g6r.ug0CAHKEyPnV5KEu.PCSjh01/xcduj5Ufntpk567lOUI0/a', 'Y', 'member@example.com'),
('contributor', '$2a$10$S.g6r.ug0CAHKEyPnV5KEu.PCSjh01/xcduj5Ufntpk567lOUI0/a', 'Y', 'staff@example.com');


-- Assign Appropriate Roles
INSERT INTO USERS_AUTHORITIES (USER_ID, AUTHORITY_TYPE_ID)
VALUES
(1,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_ADMIN')),
(1,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_CONTRIBUTOR')),
(1,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_MEMBER')),
(3,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_CONTRIBUTOR')),
(3,  (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_MEMBER')),
(2, (SELECT AUTHORITY_TYPE_ID FROM AUTHORITY_TYPE WHERE LABEL = 'ROLE_MEMBER'));

-- Insert Members
INSERT INTO MEMBERS (USER_ID, FIRST_NAME, LAST_NAME)
VALUES (
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'member'),
    'Jane',
    'Doe'
);

INSERT INTO CONTRIBUTORS (USER_ID, FIRST_NAME, LAST_NAME)
VALUES (
    (SELECT USER_ID FROM USERS WHERE USERNAME = 'contributor'),
    'alice',
    'rose'
);

INSERT INTO GENRES (LABEL) VALUES
('INDIE'),
('SHOOTER'),
('RPG'),
('MMORPG'),
('SURVIVAL'),
('ACTION'),
('MULTIPLAYER'),
('BATTLE ROYALE'),
('ADVENTURE'),
('OPEN WORLD'),
('PLATFORMER'),
('RACING'),
('FIGHTING'),
('PUZZLE'),
('STRATEGY'),
('TOWER DEFENSE'),
('SIMULATION'),
('HORROR'),
('SANDBOX'),
('MUSIC/RHYTHM'),
('CARD GAME'),
('VISUAL NOVEL'),
('SPORTS'),
('EDUCATIONAL'),
('SURVIVAL HORROR'),
('FPS'),
('TPS'),
('EXPLORATION'),
('VR'),
('ARCADE'),
('CO-OP'),
('CITY BUILDER'),
('MANAGEMENT SIMULATOR'),
('TRAINING/EDUCATIONAL'),
('CASUAL'),
('PARTY GAME'),
('MECHA'),
('ZOMBIE'),
('CYBERPUNK'),
('FANTASY'),
('SCI-FI'),
('HISTORICAL'),
('MYSTERY'),
('BOARD GAME'),
('QUIZ/TRIVIA'),
('MOBA');

-- 🎮 Consoles
INSERT INTO PLATFORMS (NAME) VALUES
('PlayStation 5'),
('PlayStation 4'),
('PlayStation 3'),
('PlayStation 2'),
('PlayStation 1'),
('Xbox Series S'),
('Xbox One'),
('Xbox 360'),
('Nintendo Switch'),
('Nintendo Wii U'),
('Nintendo Wii'),
('Nintendo 3DS'),
('Nintendo DS'),
('Game Boy Color'),
('Steam'),
('Epic Games'),
('Android'),
('iOS'),
('PlayStation Vita'),
('Nintendo GameCube'),
('Nintendo 64'),
('Sega Dreamcast');

INSERT INTO PUBLISHERS (NAME) VALUES
('UBISOFT'),
('ELECTRONIC ARTS'),
('ACTIVISION'),
('BETHESDA SOFTWORKS'),
('CAPCOM'),
('NINTENDO'),
('SONY INTERACTIVE ENTERTAINMENT'),
('MICROSOFT STUDIOS'),
('SEGA'),
('SQUARE ENIX'),
('BANDAI NAMCO'),
('TAKE-TWO INTERACTIVE'),
('ROCKSTAR GAMES'),
('CD PROJEKT'),
('EPIC GAMES'),
('BLIZZARD ENTERTAINMENT'),
('PARADOX INTERACTIVE'),
('WARNER BROS. GAMES'),
('VALVE'),
('NAUGHTY DOG'),
('INSOMNIAC GAMES'),
('BUNGIE'),
('KONAMI'),
('RIOT GAMES'),
('2K GAMES'),
('OBSIDIAN ENTERTAINMENT'),
('LIONHEAD STUDIOS'),
('DEEP SILVER');


